### ISSUE TITLE
Differences between UAT and PRD

### ISSUE THREAD

**Issue by ess-acppo-djd** [ess-acppo/ag-bie#16] opened 2018-07-12 02:13 UTC
There are some differences between the UAT implementation of the TaxaaS website (uat-ag-bie.oztaxa.com) and the PRD implementation (ag-bie.oztaxa.com):

**Formatting of search results**
individual entries consist (generally) of five lines of data as follows, with the lines noted being optional

- taxon rank followed by full taxon name (presented as a hyperlink to it's entry in the ag-BIE SOLR index)
- common names if any apply (optional)
- kingdom in which taxon is placed
- formatted name of taxon
- a link to 'view images of this species...' (optional - uncertain what triggers this inclusion)

- [x] in PRD, line 4 commences with **bold** styling, but UAT commences with _italic_ styling.
- [x] In PRD, bold styling is applied to entire lines, with no discernible pattern to it occurring.

**Sequence of search results**
- [x] search results are not presented in the same sequence.

**Data included in results**
- [x] "Biota ID" identifier is not always listed on the name tab
    - Drosophila, Biota ID 55003 is missing

**Comment by mbohun** [comment] 2018-07-19 03:35
1. one has to be **CAREFUL** to avoid back-porting the UAT **BUG** #10 into PRD
2. for the comparison I can use the UAT env to build `data-taxxas-YYYY-MM-DD_01.tar.xz`  as [we do/use](https://gist.github.com/mbohun/d6a21c6d31c66d7a517565c8caa8d454#file-ag-bie_from_scratch-md) in installing/deploying latest PRD
   - this could help us to identify the details of differences (possible problems) between the old UAT, and current (latest, stable) PRD; i.e. narrow down if the differences are caused by diff properties/config settings between the environments

**Comment by ess-acppo-djd** [comment] 2018-07-25 06:52
For the formatting, I would consider the UAT implementation to be correct.
This is a lower priority than the 'identifier' issue.

**Comment by ess-acppo-djd** [comment] 2018-08-06 03:46
When will this be promoted to SIT?
And when might it be implemented in PRD?

Note: Issue also raised in JIRA as ESP-718

**Comment by moziauddin** [comment] 2020-09-14 23:28
Data quality issues are all resolved in release 0.6

**Closed by moziauddin** 2020-09-14 23:28 UTC
Labels: bug
